### ISSUE TITLE
Missing hardware support - Killer Wireless-AC 1525 in ath10k/

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/steamos_kernel#17]
MSI are claiming out-of-the-box SteamOS Support (with a capital S) for their GAMING-series motherboards, e.g. http://www.msi.com/product/mb/X99A-GAMING-7.html#hero-overview

The OEM requirements at https://github.com/ValveSoftware/SteamOS/blob/master/OEM.md say hardware should use in-tree kernel modules only, for all hardware.

The Atheros/Killer wifi chip used by MSI on [some of their recent hardware](http://www.msi.com/product/mb/Z97I-GAMING-ACK.html#hero-overview) is NOT supported by the SteamOS kernel - it requires a 4.0 kernel (or backports from post-Alchemist ath10k/). New firmware is also required for this hardware, which is not included in the firmware packages in SteamOS.

**Comment by Tele42** [comment]
There's at least one report that this is working with Debian Jessie, so might be inherited into SteamOS Brewmaster.

**Comment by Plagman** [comment]
We're looking at switching to 4.1 at some point, would that include the right bits?

**Comment by directhex** [comment]
Yes, as long as firmware gets bumped to match

**Comment by johnv-valve** [comment]
Is this working on brewmaster 2.49?
