### ISSUE TITLE
Revert Bluetooth hack for Sony controllers in Brewmaster

### ISSUE THREAD

**Issue by Kontrabant** [ValveSoftware/steamos_kernel#23]
You can revert commit https://github.com/fledermaus/steamos_kernel/commit/7d4732c66f1fb5ddd5ec1c5b9a16f100da23a1ff in Brewmaster.  The hack was needed for the LEDs and rumble to work via Bluetooth on kernel 3.10, but as of kernel 3.15 the HID system underwent some major work to add proper support for these devices and the workaround is now unnecessary.

**Comment by Plagman** [comment]
Thanks for the heads-up!

**Comment by JoshuaMurphynz** [comment]
Now that SteamOS is based on 4.1 kernel, does this still need to be open?

**Comment by SoulEst** [comment]
No it does not.
