### ISSUE TITLE
add Killer E2400 ID in alx driver

### ISSUE THREAD

**Issue by twooden** [ValveSoftware/steamos_kernel#34]
I work for Rivet networks whom develops and distributes the Killer Networking products. We are working to upstream this change to mainline linux Kernel, but in the meantime can we have this patched in SteamOS Kernel also?

Add Killer E2400 device ID in alx driver.

Signed-off-by: Owen Lin olin@rivetnetworks.com

---

diff -uprN alx_orig/main.c alx/main.c
--- alx_orig/main.c Mon Sep  7 13:00:58 2015
+++ alx/main.c  Mon Sep  7 14:47:03 2015
@@ -1537,6 +1537,7 @@ static const struct pci_device_id alx_pc
    { PCI_VDEVICE(ATTANSIC, ALX_DEV_ID_AR8162),
      .driver_data = ALX_DEV_QUIRK_MSI_INTX_DISABLE_BUG },
    { PCI_VDEVICE(ATTANSIC, ALX_DEV_ID_AR8171) },
-   { PCI_VDEVICE(ATTANSIC, ALX_DEV_ID_E2400) },
  { PCI_VDEVICE(ATTANSIC, ALX_DEV_ID_AR8172) },
  {}
  };
  diff -uprN alx_orig/reg.h alx/reg.h
  --- alx_orig/reg.h  Mon Sep  7 13:00:58 2015
  +++ alx/reg.h   Mon Sep  7 14:46:16 2015
  @@ -39,6 +39,7 @@
  # define ALX_DEV_ID_E2200               0xe091
  # define ALX_DEV_ID_AR8162              0x1090
  # define ALX_DEV_ID_AR8171              0x10A1
  
  +#define ALX_DEV_ID_E2400               0xe0A1
  # define ALX_DEV_ID_AR8172              0x10A0
  
  /\* rev definition,

**Comment by JoshuaMurphynz** [comment]
Thank you for being so active in your Linux development. I'm sure Valve devs can merge this soon enough
