### ISSUE TITLE
add Killer E2500 ID in alx driver

### ISSUE THREAD

**Issue by twooden** [ValveSoftware/steamos_kernel#46]
I work for Rivet networks whom develops and distributes the Killer Networking products. We are about to launch (in the coming weeks), a new E2500 product and we would like to ensure these systems can load SteamOS/Linux. We are working to upstream this change to mainline linux Kernel, but in the meantime can we have this patched in SteamOS Kernel also?

Add Killer E2500 device ID in alx driver.

Signed-off-by: Thomas Wooden twooden@rivetnetworks.com

diff -uprN alx_orig/main.c alx/main.c
--- alx_orig/main.c Mon Aug 22 12:05:12 2016
+++ alx/main.c Mon Aug 22 12:27:47 2016
@@ -1537,6 +1537,7 @@ static const struct pci_device_id alx_pc
{ PCI_VDEVICE(ATTANSIC, ALX_DEV_ID_AR8162),
.driver_data = ALX_DEV_QUIRK_MSI_INTX_DISABLE_BUG },
{ PCI_VDEVICE(ATTANSIC, ALX_DEV_ID_AR8171) },

{ PCI_VDEVICE(ATTANSIC, ALX_DEV_ID_E2400) },
{ PCI_VDEVICE(ATTANSIC, ALX_DEV_ID_E2500) },
{ PCI_VDEVICE(ATTANSIC, ALX_DEV_ID_AR8172) },
{}
};
diff -uprN alx_orig/reg.h alx/reg.h
--- alx_orig/reg.h Mon Aug 22 12:05:12 2016
+++ alx/reg.h Mon Aug 22 12:27:47 2016
@@ -39,6 +39,7 @@
# define ALX_DEV_ID_E2200 0xe091
# define ALX_DEV_ID_AR8162 0x1090
# define ALX_DEV_ID_AR8171 0x10A1

+#define ALX_DEV_ID_E2400 0xe0A1
+#define ALX_DEV_ID_E2500 0xe0B1
# define ALX_DEV_ID_AR8172 0x10A0

/\* rev definition,

**Comment by johnv-valve** [comment]
Made this change in the 2.93 kernel, please verify http://steamcommunity.com/groups/steamuniverse/discussions/1/350542683209165400/
