### ISSUE TITLE
Ath10K still got the otp failure on brewmaster_beta 2.91

### ISSUE THREAD

**Issue by on6133** [ValveSoftware/steamos_kernel#49]
I have tested the brewmaster_beta 2.91 and found there is still otp failure.
There is a little difference between my patch and upstream  patch.

My patch is as below.
-  /\* Some firmware revisions have an incomplete WoWLAN implementation
-   \* despite WMI service bit being advertised. This feature flag is used
-   \* to distinguish whether WoWLAN is really supported or not.
-   */
-  ATH10K_FW_FEATURE_WOWLAN_SUPPORT = 6,
- 
-  /\* Don't trust error code from otp.bin */
-  ATH10K_FW_FEATURE_IGNORE_OTP_RESULT,
  +

Upstream patch doesn't inculde ATH10K_FW_FEATURE_WOWLAN_SUPPORT.
Please help to check this.

BR,
Owen

**Comment by johnv-valve** [comment]
are you looking in the brewmaster-4.1-proposed branch? Because that is what is shipping in beta and that does include both your pull requests with the ATH10K_FW_FEATURE_IGNORE_OTP_RESULT flag.

**Comment by on6133** [comment]
Is brewmaster_beta 2.91 base on brewmaster-4.1-proposed branch?
I have replaced the modules from my build and otp failure was fixed by new modules on brewmaster_beta 2.91.

BR,
Owen

**Comment by johnv-valve** [comment]
Yes, currently brewmaster beta is running the kernel from brewmaster-4.1-proposed.

**Comment by on6133** [comment]
It looks like ATH10K_FW_FEATURE_IGNORE_OTP_RESULT flag isn't included on brewmaster_beta 2.91.
Can you help to check this?

BR,
Owen

**Comment by superm1** [comment]
@johnv-valve 
Just a suspicion - but something seems off in your build system.  There's stuff in _brewmaster-4.1_ that's not in _brewmaster-4.1-proposed_ but also stuff in _brewmaster-4.1-proposed_ not in _brewmaster-4.1_

The commits you merged were added to _brewmaster-4.1-proposed_ that I can tell, but the build that was part of 2.91 doesn't seem to include them properly.
- I fetched the latest source package http://repo.steampowered.com/steamos/pool/main/l/linux/linux_4.1.13-0+steamos10.debian.tar.xz and extracting shows the most  recent changelog entries:

```
linux (4.1.13-0+steamos10) brewmaster; urgency=low

  * Git snapshot 416b1d2b0db564a8dcc3391c3e8343b9d15e1c08

 -- ValveBot <noreply@valvesoftware.com>  Mon, 29 Aug 2016 16:18:47 -0700

linux (4.1.13-0+steamos9) brewmaster; urgency=low

  * Git snapshot 416b1d2b0db564a8dcc3391c3e8343b9d15e1c08

 -- ValveBot <noreply@valvesoftware.com>  Mon, 15 Aug 2016 17:43:03 -0700


```

That commit (`416b1d2b0db564a8dcc3391c3e8343b9d15e1c08`) is what's currently the HEAD of brewmaster-4.1.  https://github.com/ValveSoftware/steamos_kernel/commit/416b1d2b0db564a8dcc3391c3e8343b9d15e1c08

It's not actually present in _brewmaster-4.1-proposed_ as it stands today.  
So I believe that Owen is right that there is some problem here.  Can you check what's actually going on?

**Comment by superm1** [comment]
@johnv-valve Any updates on this?

**Comment by johnv-valve** [comment]
been out of the office, looking into it now

**Comment by johnv-valve** [comment]
Please try the 2.93 that just shipped http://steamcommunity.com/groups/steamuniverse/discussions/1/350542683209165400/

**Comment by superm1** [comment]
Reports say that seems to fix the OTP issue.  This particular issue can be closed.

**Comment by superm1** [comment]
@johnv-valve Was there anything else added into ath10k between 2.93 and 2.95?  It seems that there are some other problems with the killer 1535 not working properly for Wifi that are now different than the OTP issue.

You should have a sample of this HW we sent, can you take a look on your end maybe?

**Comment by johnv-valve** [comment]
as far as I know this is all working now
