### ISSUE TITLE
GFP_KERNEL used in interrupt context. 

### ISSUE THREAD

**Issue by computerquip** [ValveSoftware/steamos_kernel#5]
I noticed on line 635 in xpad.c that you call xpad360w_process_packet... however, this function allocates memory using GFP_KERNEL. This can cause a sleep which is an issue in interrupt context.

**Comment by Plagman** [comment]
You're right, this needs to be cleaned up. Thanks for the report!

**Comment by computerquip** [comment]
Unless this issue tracker is no longer being used, why was this closed?
