### ISSUE TITLE
Something that I've noticed about this repository is that it has really old files that have nothing to do with the hardware SteamOS runs on.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steamos_kernel#50]
Essentially, what I am seeing in this repo is the base Debian repository with the addition of new driver files (which is great). However, the base Debian repository and distribution therein has way too many old drivers that have nothing to do with Steam, nor will Steam execute on that hardware of that era. Also, you have chipsets under the Arch folder which is designed so that you can port the OS over to each of these different system. Problem is, some of these systems don't have enough memory to even run Steam, let alone games created for it.

My suggestion is to cut the old technology files and architectures you never plan on supporting, which will make your project smaller and even more customized. There will be a lot less "configure" flags to fiddle around with. By chopping out the old dead wood, it should make it a lot easier to maintain.

An example of what I am taking about is the EISA busline, it predates the PCI and PCI-E. As you've stated the recommended hardware, will have PCI-E slots in it, the least you should support are the original PCI slots, nothing older. That will also cut down on the amount of CPUs you need to support as well because you find certain families with the minimum of PCI v1.00 , Intel AGP and beyond.

**Comment by Plagman** [comment]
Chopping old files would increase our difference from the base kernel tree and make everything harder to maintain.
