### ISSUE TITLE
[2.117] Kernel oops when connecting DualShock 4 (054C:05C4)

### ISSUE THREAD

**Issue by flibitijibibo** [ValveSoftware/steamos_kernel#53]
Copypasting from the [2.117 announcement thread](https://steamcommunity.com/groups/steamuniverse/discussions/1/1291817837636983784/)...

There appears to be a regression from the kernel's recent updates/changes to hid-sony.c. Connecting a DS4 via Bluetooth causes the system (and the controller) to lock up; here's the relevant dmesg output:

https://gist.github.com/flibitijibibo/1369c7da5b922983c7fbdcf336ea3921

It's reproducible with a USB connection, and I've duplicated this on a different PC running 2.117. AFAIK this is 100% reproducible with an original DualShock 4 controller.

**Comment by flibitijibibo** [comment]
This is entirely a guess, but I'm looking at the new hid-sony file and saw this...

https://github.com/ValveSoftware/steamos_kernel/blob/7aabed00fe8659d908627aec19c6bf055d5264c1/drivers/hid/hid-sony.c#L2788

Aren't these just bitmask constants? Looking around the rest of the file it should be this instead:

```
	/*
	 * On suspend save the current LED state,
	 * stop running force-feedback and blank the LEDS.
	 */
	struct sony_sc *sc = hid_get_drvdata(hdev); /* FIXME: Check NULL? -flibit */

	if (sc->quirks & SONY_LED_SUPPORT) {
		memcpy(sc->resume_led_state, sc->led_state,
			sizeof(sc->resume_led_state));
		memset(sc->led_state, 0, sizeof(sc->led_state));
	}

#ifdef CONFIG_SONY_FF
	if (sc->quirks & SONY_FF_SUPPORT) {
		sc->left = sc->right = 0;
	}
#endif

	sony_send_output_report(sc);

	return 0;
```

Same issue applies to sony_resume as well. I'm thinking this crash has to do with some uninitialized data that's getting run over because these if statements are always true no matter what.

**Comment by flibitijibibo** [comment]
Built the latest version and for whatever reason it still fails - even adding a NULL check explodes. I isolated the function to this patch:

https://github.com/ValveSoftware/steamos_kernel/commit/decd946c99f6b3826bda0bfd5d1b2ddd56ef6b54

Since this doesn't appear to actually work (nor should it have even when it was new), and also doesn't seem to work in the way you might expect (wouldn't we want to turn the device off entirely for wireless devices...?), it may be easier to just strip this out and implement this later.

**Comment by johnv-valve** [comment]
it's a red herring, the real bug is sony_get_js_number() which is busted now. Backing this out until we have a chance to revisit it.

**Comment by flibitijibibo** [comment]
Latest `staging` revision works! Once this is published we can mark this as done.

**Comment by johnv-valve** [comment]
fixed in today's beta release http://steamcommunity.com/groups/steamuniverse/discussions/1/2333276539589853731/
