### ISSUE TITLE
[Request] Kernel version 4.11 when 4.15 is out

### ISSUE THREAD

**Issue by xsellier** [ValveSoftware/steamos_kernel#54]
Greetings,

Thank you for your amazing job. For real, I enjoy what you've done so far with Debian GNU/Linux.
I would enjoy the latest improvements from the kernel 4.15, and I hope Valve will update the SteamOS kernel anytime soon.

So here is my request/question, is there any ETA for the next kernel update ?

Regards

**Comment by johnv-valve** [comment]
4.15 is not even released yet and will probably not be for another two months. So any ETA for 4.15 would be after that.
