### ISSUE TITLE
Waiting for 4.16 source, here on github

### ISSUE THREAD

**Issue by Lepidos** [ValveSoftware/steamos_kernel#55]
steamos_kernel Github releases has been outdated for a while... :(

**Comment by TTimo** [comment]
Right, thanks for bringing that to our attention.

The latest brewmaster kernel source is always available from the apt repository: http://repo.steampowered.com/steamos/

We haven't been updating this git tree for various reasons. I think we'll start pushing updates to it again soon.

**Comment by TTimo** [comment]
https://github.com/ValveSoftware/steamos_kernel/tree/brewmaster-4.19
